name: WhatsApp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  shared_preferences: ^0.5.12+4

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  modal_bottom_sheet: ^1.0.0+1

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png
